# This is a basic workflow to help you get started with Actions

name: cloc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - name: Work around permission issue
        run: git config --global --add safe.directory '/home/user/DSTServerManager'
      - name: Get repository
        uses: actions/checkout@v3
      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@3
